### ISSUE TITLE
Cyrillic topic results in 500

### ISSUE THREAD

**Issue by ChaikaBogdan** [onipot/K-Stash#2]
<img width="1505" alt="Screenshot 2020-09-07 at 12 19 13" src="https://user-images.githubusercontent.com/16524061/92371590-739c2e80-f104-11ea-88fe-8203a3f9370d.png">

**Issue**: you cannot save resources with title in RU (Cyrillic)
I was trying to add https://habr.com/ru/company/yandex/blog/517266/ to one of my topics, using autogenerated topic name in RU, but it wont save.

**Test reference:**  
**Resource link:** https://habr.com/ru/company/yandex/blog/517266/
**Resource tittle:** any RU will do, for example - "Тесты в Python: все основные подходы, плюсы и минусы. Доклад Яндекса"

After pressing **Add** i am getting:

https://k-stash.com/addres
**Status** - **500**,
**Preview:** 
```
"Illuminate\Database\QueryException"
file: "/home/kstavqna/public_html/kstash/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
line: 671
message: "SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: 
```
**Response:**
```
   "message": "SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xD1\\x84\\xD1\\x8B\\xD0\\xB0...' for column `kstavqna_kstash`.`resource`.`titolo` at row 1 (SQL: insert into `resource` (`contenuto`, `topic_id`, `data`, `titolo`, `extra`) values (https://habr.com/ru/company/yandex/blog/517266/, 89, 2020-09-07, \u0444\u044b\u0430\u044b\u0430, ))",
    "exception": "Illuminate\\Database\\QueryException",
    "file": "/home/kstavqna/public_html/kstash/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
    "line": 671,
```

**Can you, please, add Cyrillic support?**

**Comment by masc-it** [comment]
Thank you for your report @ChaikaBogdan !
I should have fixed it, try now and let me know!

**Comment by ChaikaBogdan** [comment]
@onipot Cyrillic save is fixed.

But on auto-title-generation getting empty response from https://k-stash.com/scrapetitle
**url:**  https://habr.com/ru/company/yandex/blog/517266/ 

Might be side-effect of fix? Works before...

**Comment by masc-it** [comment]
@ChaikaBogdan Just tried with your link and it works (for me), the target website might be slow, so try clicking multiple times until you get it

**Comment by ChaikaBogdan** [comment]
@onipot  its all about spaces in beginning or end of url
can you please trim them?)

**Comment by masc-it** [comment]
> @onipot its all about spaces in beginning or end of url
> can you please trim them?)

try now

**Comment by ChaikaBogdan** [comment]
space before url results in:
https://k-stash.com/scrapetitle 500 "message": "file_get_contents( https://habr.com/ru/company/yandex/blog/517266/): failed to open stream: No such file or directory",

**Comment by masc-it** [comment]
> space before url results in:
> https://k-stash.com/scrapetitle 500 "message": "file_get_contents( https://habr.com/ru/company/yandex/blog/517266/): failed to open stream: No such file or directory",

I am applying both ltrim and rtrim to the url

**Comment by masc-it** [comment]
@ChaikaBogdan Ok, client-side trimming did the trick. Check and let me know

**Comment by ChaikaBogdan** [comment]
@onipot  fixed, but...i know i am annoying but search doesn't work with Cyrillic too
https://k-stash.com/search 500 on "фыфыв" search

Also little note, if parsing for auto-title takes 0.5-2s can you add some "processing" spinner on button and actually block button event? Speed-clickers like me, can click 1-3 times in anxiety, because "is it working even?"

**Comment by masc-it** [comment]
@ChaikaBogdan absolutely no problems, love users like you that give consutctive feedbacks and reports. Please, just create new separate issues :)

As temporary answer to these reports: I am working on them.
