### ISSUE TITLE
Add timeout to auto-title and prevent 500

### ISSUE THREAD

**Issue by ChaikaBogdan** [onipot/K-Stash#6]
**Test data:** https://www.youtube.com/watch?v=6VBCXvfNlCM&feature=youtu.be
1) Try to add this link as resource to any topic
2) Wait until auto-title will be grabbed

**Expected:** It will timeout in 5-10s and **allow you to set topic manually**
**Actual:**  It will stuck, with https://k-stash.com/scrapetitle 500

    "message": "file_get_contents(https://www.youtube.com/watch?v=6VBCXvfNlCM&amp;feature=youtu.be): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests\r\n",
    "exception": "ErrorException",
    "file": "/home/kstavqna/public_html/kstash_git/app/Http/Controllers/Stash.php",
    "line": 53,

**Comment by masc-it** [comment]
working on this right now!

**Comment by masc-it** [comment]
@ChaikaBogdan pushed changes. Unfortunately the current method just returns "YouTube" for yt links. In future I will fix this too. Stay tuned!

**Comment by masc-it** [comment]
Fixed with [v0.5-beta](https://github.com/onipot/K-Stash/releases/tag/v0.5-beta)
