### ISSUE TITLE
Preserve currently searched topics after resource add

### ISSUE THREAD

**Issue by ChaikaBogdan** [onipot/K-Stash#7]
1) You have many topics
2) You searching for topic not visible right now
3) You adding new resource to it
**Expected:**  You can add resource to same topic, items you searched - stay
**Actual:** topic list resets, your search result are gone, you need to search again.
https://www.loom.com/share/36545d22da664cd986a2682cd095cd56

**Comment by masc-it** [comment]
adding this to todo list

**Comment by masc-it** [comment]
Fixed with [v0.5-beta](https://github.com/onipot/K-Stash/releases/tag/v0.5-beta)
