### ISSUE TITLE
Show all Topics on initial homepage load, not only 10

### ISSUE THREAD

**Issue by ChaikaBogdan** [onipot/K-Stash#8]
**Precondition:** You have more than 10 topics
1) Go to https://k-stash.com/home
**Expected:** you can see all topics
**Actual:** you can see only 10

2) Try to search with empty string - you will see them all with scroll **(which is good)**

**Note:** its just confusing after revisiting homepage, like "where all my stuff gone?", as home page doesn't  mention how much it showing right now (maybe add current/overall counter?)

**Comment by masc-it** [comment]
Fixed with [v0.5-beta](https://github.com/onipot/K-Stash/releases/tag/v0.5-beta)
